# Generated by Django 3.0rc1 on 2019-12-27 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='username',
            new_name='user',
        ),
    ]
