# Generated by Django 3.0rc1 on 2019-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191227_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='status',
            new_name='activation',
        ),
    ]
