# Generated by Django 3.0rc1 on 2020-01-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200104_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
